name: 'Docs Preview (Build)'

on:
  workflow_call:
    inputs:
      preview-context:
        description: 'Preview Metadata (JSON)'
        required: true
        type: string

env:
  # Build output directory (created by the mkdocs-material container, keep this in sync with `build-docs.sh`):
  BUILD_DIR: ${{ fromJSON( inputs.preview-context ).build_dir }}
  # These two are only needed to construct `PREVIEW_URL`:
  PREVIEW_SITE_NAME:   ${{ fromJSON( inputs.preview-context ).netlify.site_name     }}
  PREVIEW_SITE_PREFIX: ${{ fromJSON( inputs.preview-context ).netlify.deploy_prefix }}

permissions:
  # Required by `actions/checkout` for git checkout:
  contents: read

jobs:
  prepare-preview:
    name: 'Build Preview'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      # ================== #
      # Build docs preview #
      # ================== #

      # CAUTION: Security risk due to executing `build-docs.sh` (which a PR could modify to be malicious):
      # Care must be taken to run this workflow as if it were in an untrusted context (like the `on: pull_request` event trigger would).
      - name: 'Build with mkdocs-material via Docker'
        working-directory: docs/
        env:
          PREVIEW_URL: 'https://${{ env.PREVIEW_SITE_PREFIX }}--${{ env.PREVIEW_SITE_NAME }}.netlify.app/'
        run: |
          # Adjust `mkdocs.yml` for the preview build requirements:
          # - Replace production `site_url` with the preview URL (only affects the canonical link: https://en.wikipedia.org/wiki/Canonical_link_element#HTML)
          # - Prepend Netlify logo link to `copyright` content
          sed -i "s|^site_url:.*|site_url: '${{ env.PREVIEW_URL }}'|" mkdocs.yml

          # Insert branding into page content (Netlify OSS plan requirement):
          # - `mkdocs-material` does not provide a better way to do this.
          # - Prepends HTML to the copyright text and then aligns the logo to the right-side of the page.
          NETLIFY_BRANDING='<a href="https://www.netlify.com/"><img alt="Deploys by Netlify" src="https://www.netlify.com/img/global/badges/netlify-color-accent.svg" style="float: right;"></a>'
          sed -i "s|^copyright: '|copyright: '${NETLIFY_BRANDING}|" mkdocs.yml
          # Override a CSS media query for the parent element to always be full width:
          echo '.md-footer-copyright { width: 100%; }' >> content/assets/css/customizations.css

          # Build and prepare for upload:
          echo "::group::Build (stdout)"
          bash ../.github/workflows/scripts/docs/build-docs.sh
          echo "::endgroup::"

      # ============================== #
      # Volley over to secure workflow #
      # ============================== #

      # Archives directory `path` into a ZIP file:
      - name: 'Upload artifact for workflow transfer'
        uses: actions/upload-artifact@v4
        with:
          name: preview-build
          path: ${{ env.BUILD_DIR }}
          retention-days: 1
